/* REPLACE_MADP_HEADER */
/* REPLACE_CONTRIBUTING_AUTHORS_START
 * Frans Oliehoek 
 * Matthijs Spaan 
 * REPLACE_CONTRIBUTING_AUTHORS_END
 */

#ifndef _BGBACKUPTYPE_H_
#define _BGBACKUPTYPE_H_ 1

enum BGBackupType { EXHAUSTIVE_ONLYKEEPMAX,
                    EXHAUSTIVE_STOREALL,
                    BGIP_SOLVER_EXHAUSTIVE,
                    BGIP_SOLVER_ALTERNATINGMAXIMIZATION,
                    BGIP_SOLVER_ALTERNATINGMAXIMIZATION_100STARTS,
                    BGIP_SOLVER_BRANCH_AND_BOUND
};

#endif /* !_BGBACKUPTYPE_H_ */
