#!/bin/bash
# GMAA-ICE means calling GMAA with BG clustering enable and using an
# incremental BGIP solver, in this case BaGaBaB

$(dirname -- "$0")/GMAA --GMAA=MAAstar --useBGclustering --BGIP_Solver=BnB --BnB-ordering=Prob $@
